services:
  - type: web
    name: fairhire-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "cd backend && gunicorn app:app"
    plan: free
    envVars:
      - key: GEMINI_API_KEY
        sync: false
